### ISSUE TITLE
Notice of commercially licensed code in your GitHub repository

### ISSUE THREAD

**Issue by rc-d** [prioritypie/moretoit#1]
Hello, you've got a copy of my commercial module FormBuilder in your /site/modules/FormBuilder/ directory on this repository. This module is not meant for public distribution. Would you please remove it at your earliest convenience? Thanks, –Ryan

**Comment by prioritypie** [comment]
Yikes! Something lying around from the past that should never have been here in the first place! I will remove the whole repo I think.
Sorry for any trouble caused, it was certainly not intentional.
